---
- name: Ensure user "{{ new_username }}" is created with superuser privileges
  user:
    name: "{{ new_username }}"
    groups: sudo
    append: yes
    create_home: yes
    shell: /usr/bin/zsh
    state: present
  become: true

- name: Set authorized keys for "{{ new_username }}"
  authorized_key:
    user: "{{ new_username }}"
    state: present
    key: "https://github.com/{{ new_username }}.keys"
  become: true
