---
- name: Ensure user "{{ username }}" is created with superuser privileges
  user:
    name: "{{ username }}"
    groups: sudo
    append: yes
    create_home: yes
    shell: /usr/bin/zsh
    state: present
  become: true

- name: Set authorized keys for "{{ username }}"
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "https://github.com/{{ github_username }}.keys"
  become: true
