- hosts: new
  roles:
    - role: install-packages
      packages: [git, curl, htop, ufw]
    - role: create-user-with-ssh-access
    - role: configure-sudo-without-password
    - role: configure-firewall
      become: true
    - role: configure-oh-my-zsh
    - role: configure-oh-my-tmux
    - role: install-docker-ce-with-compose
      become: true
      docker_edition: 'ce'
      docker_package_state: present
      docker_install_compose: true
    - role: configure-docker
    - role: secure-ssh-config

  handlers:
    - import_tasks: ../handlers/ssh.yml
